config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'

  resources :user

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, allow_blank: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.create
    redirect_to edit_user_path(@user.id)
  end

  def edit
    @user = User.find_by(id: params[:id])
    @user.valid? if @user.created_at != @user.updated_at
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Untitled
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag

    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-dark.bg-dark{:style => "background-color: #e3f2fd;"}
      .container
        = link_to 'PartingPro', root_path, class: 'navbar-brand'

    .container
      = yield

app/views/user/_form.html.haml
.row#form-edit-user
  .col-2
  .col-8
    .pt-5
      = simple_form_for(user,
          defaults: { input_html: { data: { reflex: "debounced:input->user#update", signed_id: user.to_sgid.to_s } } }) do |f|
        - custom_message = ->(attribute_name) { f.object.errors.full_messages_for(attribute_name).to_sentence }

        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :first_name, class: 'form-control', error: custom_message.call(:first_name)

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :last_name, class: 'form-control', error: custom_message.call(:last_name)

        .mb-2.pt-2
          = f.input :middle_name, class: 'form-control', error: custom_message.call(:middle_name)

        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :phone_number, class: 'form-control', error: custom_message.call(:phone_number)

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :email, class: 'form-control', error: custom_message.call(:email)

        .mb-2.pt-2
          = f.input :social_security_number, class: 'form-control', error: custom_message.call(:social_security_number),
              input_html: { class: 'input-ssn' }

        .mb-2.pt-2
          = f.input :country, as: :select, required: false,
                collection: ['United States', 'Other'], include_blank: false,
                selected: f.object.country ? f.object.country : 'United States',
                error: custom_message.call(:country)

        .mb-2.pt-2#other_country
          = f.input :other_country, class: 'form-control', error: custom_message.call(:other_country)

        .mb-2.pt-2
          = f.input :address, class: 'form-control', error: custom_message.call(:address)
        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :city, class: 'form-control', error: custom_message.call(:city)

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :state, class: 'form-control', error: custom_message.call(:state)

        .mb-2.pt-2
          = f.input :zip_code, label: "Zip code", class: 'form-select', error: custom_message.call(:zip_code)


    .mb-2.text-end
      = link_to 'Back', root_path, class: 'button btn btn-primary'

:javascript
  let countrySelector = document.getElementById("user_country");
  let country = countrySelector.value;
  let other_country = document.getElementById("other_country");
  let outher_country_input = document.getElementById("user_other_country");

  function handle_country() {
    let countrySelector = document.getElementById("user_country");
    let country = countrySelector.value;
    let other_country = document.getElementById("other_country");
    let outher_country_input = document.getElementById("user_other_country");

    if (country == "United States") {
      outher_country_input.value = "";
      outher_country_input.dispatchEvent(new Event('input'));
    }
    display_other_country();
  };

  function show_other_country(other_country) {
    other_country.classList.remove("not-displayed");
  }

  function hide_other_country(other_country) {
    other_country.classList.add("not-displayed");
  }

  function display_other_country() {
    let countrySelector = document.getElementById("user_country");
    let country = countrySelector.value;
    let other_country = document.getElementById("other_country");

    if(country == "United States") {
      hide_other_country(other_country);
    } else if (country == "Other") {
      show_other_country(other_country);
    }
  }

  countrySelector.addEventListener("change", display_other_country);

  document.addEventListener("cable-ready:after-morph", handle_country);
  document.addEventListener("DOMContentLoaded", display_other_country);

app/views/user/edit.html.haml
%div#edit-user
  = render partial: 'user/form', locals: { user: @user}

app/views/user/index.html.haml
.pt-5
.container
  .pt-2.text-end
    = link_to 'Create User', new_user_path, class: 'btn btn-primary'
  %table.table
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} First name
        %th{:scope => "col"} Last name
        %th{:scope => "col"} email
        %th{:scope => "col"}
    %tbody#users-list
      - @users.each do |user|
        %tr{ data: { signed_id: user.to_sgid.to_s } }
          %th{:scope => "row"} 1
          %td= user.first_name
          %td= user.last_name
          %td= user.email
          %td.text-end.pe
            %span
              = link_to 'Edit', edit_user_path(user), class: 'btn btn-outline-info me-3'
              %a.button.btn.btn-outline-danger{ href: "#", data: { reflex: "click->user#destroy", signed_id: user.to_sgid.to_s } } Remove